config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'pages#home'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete'login', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories

    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true,length: {minimum: 10, maximum: 300}

end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
    belongs_to :article
    belongs_to :category
    
end
  

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories


    validates :name, presence: true, length: {minimum: 3, maximum: 26}
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :articles, dependent: :destroy

    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimun: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||=User.find(session[:user_id]) if session[:user_id]
            
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[ edit update destroy ]

  # GET /articles/1 or /articles/1.json
  def show
    
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @article = Article.new
  end

  def edit
    
  end

  def create
      byebug
      @article = Article.new(article_params)
      @article.user = current_user
      if @article.save
        flash[:notice] = "Atricle created!!, #{@article.category_ids}"
        redirect_to @article    
     else
        render 'new'
     end
  end


  def update
    if (@article.update(article_params))
      flash[:notice] = "Article updated!!"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  
  def set_article
    @article = Article.find(params[:id])
  end


  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin
      flash[:alert] = "You can only edit your articles"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index,:show]
    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was created"   
            redirect_to @category      
        else
           render 'new'
        end

    end


    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end


    def edit
        @category = Category.find(params[:id])
    end

    def update
       @category = Category.find(params[:id])
       if (@category.update(category_params))
           flash[:notce] = "Category name updated"
           redirect_to @category
       else
        render 'edit'
       end
    end
    private

    private
    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
       if  !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can perform this action"
            redirect_to categories_path
       end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


    def home
        redirect_to articles_path if logged_in?
    end

    def about
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end


    def create

        user = User.find_by(email: params[:session][:email].downcase)
        
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice]= "user loged in"
            redirect_to(user)
        else
            flash.now[:alert] = "Login details incorrect!"
            render 'new'
        end
            
    end


    def destroy
        session[:user_id] = nil
        flash[:notice]= "user loged in"
        redirect_to root_path
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user, only: %i[ edit update destroy ]
  before_action :require_same_user,  only: %i[ edit update destroy ]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5) 
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)  
  end

  def new
      @user = User.new
  end

  def edit
    
  end

  def update
    if (@user.update(user_params))
      flash[:notice] = "Profile updated!!"
      redirect_to @user
    else
      render 'edit'
    end
  end


  def create
    @user = User.new(user_params)
    if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "User #{@user.username} Created. Welcome to Alpha Blog!!"
        redirect_to articles_path
    else
        render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if current_user == @user 
    flash[:notice] = "Account and all articles deleted"
    redirect_to articles_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end


  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit your profile"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user,options={size: 80})
        size = options[:size]
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username,class:"rounded shadow mx-auto d-block") 
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="conteiner">
    <% @articles.each do |article| %>
        <div class="row justify-content-md-center ">
          <div class="col-8 mt-4">  
              <div class="card text-center shadow"> 
                    <div class= "card-header font-italic">
                        by <%= link_to article.user.username, user_path(article.user) %>
                        <% if article.categories.any? %>
                            <div class="mt-2"> <%= render article.categories %> </div>                    
                        <% end %>
                    </div>                 
                    <div class="card-body">
                      <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
                      <p class="card-text"><%= truncate(article.description, lenght: 50)%></p>
                      <%= link_to 'Show', article_path(article), class: "btn btn-outline-primary"%>
                      <% if logged_in? && (current_user == article.user || current_user.admin? ) %>
                        <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-success"%>
                        <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "are you sure?"},class: "btn btn-outline-danger" %>
                      <%end%>
                    </div>
                    <div class="card-footer text-muted">
                     <small>Created <%= time_ago_in_words(article.created_at) %> ago by </small>
                    </div>
            </div>
          </div>
        </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article) do |form| %>
<div class="container mt-3 ">
 <%= render 'shared/errors' , obj: @article%>
 <div class="input-group m-1">   
   <%= form.label :title, class:"input-group-text"  %>
   <%= form.text_field :title, class:"form-control", placeholder:"Title for article" %>
 </div>

  <div class="input-group m-1">
    <%= form.label :description, class:"input-group-text" %>
    <%= form.text_area :description, rows:10, class:"form-control",placeholder:"The info of the article"  %>
  </div>

  <div class="input-group m-1">
    <%= form.label :category, class:"input-group-text" %>
    <%= form.collection_select(:category_ids, Category.all, :id, :name, 
                              {prompt: "Select from the list below (can be empty)"} ,{multiple: true, class: "form-select form-control"} ) %>
    
   
  </div>

  <div class="input-group m-1 gap-2">
    <div class="actions">
      <%= form.submit class:"btn btn-primary" %>
    </div>  
  </div>

</div>
<% end %>
<div class="d-grid gap-2">
    <%= link_to '[Cancel and go back to the article list]', articles_path, class: "btn btn-outline-dark" %>
</div>

app/views/articles/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Create an Article</h1>

<%= render 'form', article: @article %>

   
</div>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles listing page</h1>
  
  <div class="flickr_pagination mt-4">
    <%= will_paginate @articles, :container => false %>
  </div>
    
  <%= render 'article' %>
  
  <div class="flickr_pagination mb-4 mt-4">
    <%= will_paginate @articles, :container => false %>
  </div>
  
<div class="d-grid gap-2 mt-4 mb-2">
 <%= link_to 'Create a new article', new_article_path,class: "btn btn-outline-dark " %> 
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create an Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="conteiner">
   <h2 class="text-center mt-4"> <%= @article.title%> </h2>
   <div class="row justify-content-md-center ">
      <div class="col-8 mt-4">
         <div class="card text-center shadow">
           <div class= "card-header font-italic">
                      by <%= @article.user.username %>
                      <%= link_to gravatar_for(@article.user, size:50), user_path(@article.user)%>
                      <% if @article.categories.any? %>
                       <div class="mt-2"> <%= render @article.categories %> </div>                    
                      <% end %>
               </div>
            <div class="card-body">
                  
               <div class="card-text text-start"><%= simple_format(@article.description) %></div>
               <hr>
                <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
                  <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-success"%>
                  <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "are you sure?"},class: "btn btn-outline-danger" %>
               <% end %>
            </div>
            <div class="card-footer text-muted">
               <small>Created <%= time_ago_in_words(@article.created_at) %> ago by </small>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge bg-info text-dark" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category) do |form| %>
<div class="container mt-3 ">
 <div class="input-group m-1">   
   <%= form.label :name, "Category Name", class:"input-group-text"  %>
   <%= form.text_field :name, class:"form-control", placeholder:"Category name here" %>
 </div>

  <div class="input-group m-1 gap-2">
    <div class="actions">
      <%= form.submit class:"btn btn-primary" %>
    </div>  
  </div>
</div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Editing a category <b> <%= @category.name %> </b> </h1>

<div class = "container" >
  <%= render 'form' %>
</div>

<div class="d-grid gap-2">
    <%= link_to '[Cancel and go back to the category]', category_path(@category), class: "btn btn-outline-dark" %>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories listing page</h1>

<div class="flickr_pagination mt-4">
<%= will_paginate @categories, :container => false %>
</div>

<div class="conteiner">
    <% @categories.each do |category| %>
        <div class="row justify-content-md-center ">
          <div class="col-4 mt-4">  
              <div class="card text-center shadow"> 
                    <div class="card-body">
                      <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
                       <p class="card-text"><%= pluralize(category.articles.count,"article")%></p>
                    </div>
                    <div class="card-footer text-muted">
                     <small>Created <%= time_ago_in_words(category.created_at) %> ago by </small>
                    </div>
            </div>
          </div>
        </div>
    <% end %>
</div>

<div class="flickr_pagination mb-4 mt-4">
<%= will_paginate @categories, :container => false %>
</div>

<div class="d-grid gap-2 mt-4 mb-2">
 <%= link_to 'Create a new category', new_category_path,class: "btn btn-outline-dark " %> 
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>
<div class = "container" >
  <%= render 'form' %>
</div>
<div class="d-grid gap-2">
    <%= link_to '[Cancel and go back to the categories list]', categories_path, class: "btn btn-outline-dark" %>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<div class="text-center mt-4">
    <% if logged_in? && current_user.admin? %>
      <%= link_to "Edit category name", edit_category_path(@category), class:"btn btn-outline-success" %>
    <% end %>
</div>

<div class="flickr_pagination mt-4">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mt-4 mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
    <span class="text-muted">Some copyright</span>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name,msg| %>
    <% if name == "notice" %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
    <% elsif name == "alert" %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <% else %>
      <div class="alert alert-info alert-dismissible fade show" role="alert">
    <% end %>
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <%end%>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <%=  link_to 'Alpha Blog', root_path, class: "navbar-brand", id:"logo" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <%= link_to 'Bloggers', users_path, class: "nav-link active" %></li>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Articles
                </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><%= link_to 'Article List', articles_path, class: "dropdown-item" %></li>
                    <% if logged_in? %>
                        <li><hr class="dropdown-divider"></li> 
                        <li><%= link_to 'New article', new_article_path,class: "dropdown-item" %> </li>
                    <%end%>
                    
                </ul>
            </li>
             <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categories
                </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><%= link_to 'Categories List', categories_path, class: "dropdown-item" %></li>
                    <% if logged_in? && current_user.admin? %>
                        <li><hr class="dropdown-divider"></li> 
                        <li><%= link_to 'New category', new_category_path,class: "dropdown-item" %> </li>
                    <%end%>
                    
                </ul>
            </li>
            <% if logged_in? %>
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                 <%= "[Admin]" if current_user.admin %> Profile <%= current_user.username %>
                </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li class="nav-item">
                            <%= link_to 'Log out', login_path, class: "nav-link active", method: :delete %></li>
                        </li>
                        <li><hr class="dropdown-divider"></li> 
                        <li class="nav-item">
                            <%= link_to "View your profile", user_path(current_user), class: "nav-link active" %></li>
                            <%= link_to "Edit your profile", edit_user_path(current_user), class: "nav-link active" %></li>
                            <hr class="dropdown-divider">
                            <%= link_to "Delete your profile", user_path(current_user), class: "nav-link active text-danger", method: :delete, data: {confirm: "Are you sure?"} %></li>
                        </li>
                    </ul>
                </li>
                
            <%else%>
                <li class="nav-item">
                    <%= link_to 'Log in', login_path, class: "nav-link active" %></li>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sing in', signup_path, class: "nav-link active" %></li>
                </li>
            <%end%>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render './layouts/navigation' %>
    <div id="page-content">
      <%= render './layouts/messages' %>
      <%= yield %>
    </div>
    <%= render './layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container" id="home-container">
    <div class="p-5 mb-4 bg-light rounded-3" id="jumbo-home">
        <div class="container-fluid py-5 text-white">
            <h1 class="display-5 fw-bold text-center">Alpha blog</h1>
            <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
            <%= link_to "Sign up!", signup_path,  class:"btn btn-primary btn-lg" %>
        </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
   <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4><%= pluralize(obj.errors.count, "error") %> prohibited this <%= obj.class.name.downcase %>  from being saved:</h4>
        <hr>
        <ul>
          <% obj.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
   </div>

<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |form| %>
<div class="container mt-3 ">
 <%= render 'shared/errors', obj: @user %>
 <div class="input-group m-1">   
   <%= form.label :username, class:"input-group-text"  %>
   <%= form.text_field :username, class:"form-control", placeholder:"Your username here" %>
 </div>

 <div class="input-group m-1">   
   <%= form.label :email, class:"input-group-text"  %>
   <%= form.email_field :email, class:"form-control", placeholder:"Your email" %>
 </div>

  <div class="input-group m-1">
    <%= form.label :password, class:"input-group-text" %>
    <%= form.password_field :password, class:"form-control", placeholder:"super strong password" %>
  </div>

  <div class="input-group m-1 gap-2">
    <div class="actions">
      <%= form.submit(@user.new_record? ? "Sing up" : "Update Profile", class:"btn btn-primary") %>
    </div>  
  </div>
</div>
<% end %>
<div class="d-grid gap-2">
    <%= link_to '[Cancel and go back to the article list]', articles_path, class: "btn btn-outline-dark" %>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit you profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4"> Bloggers List </h1>
<div class="flickr_pagination mt-4">
  <%= will_paginate @users, :container => false %>
</div>

<div class="conteiner">
    <% @users.each do |user| %>
        <div class="row justify-content-md-center ">
          <div class="col-8 mt-4">  
              <div class="card text-center shadow"> 
                    <div class= "card-header font-italic">
                     <%= link_to user.username, user, class: "btn btn-outline-primary"%> 
                    </div>                 
                    <div class="card-body">
                      <h5 class="card-title">
                         <%= link_to gravatar_for(user,size:150), user, class: "btn btn-outline-primary"%> 
                      </h5>
                      <p class="card-text"><%= pluralize(user.articles.count,"article")%></p>
                      <%= link_to "view #{user.username} profile", user, class: "btn btn-outline-primary"%> 
                     <% if logged_in? %>
                          <% if current_user == user  %>
                            <%= link_to 'Edit Profile', edit_user_path(user), class: "btn btn-outline-success"%>
                          <% end %>
                          <% if current_user.admin?  %>
                            <%= link_to 'Delete User', user_path(user), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"}%>
                          <% end %>
                      <% end %>
                    </div>
                    <div class="card-footer text-muted">
                     <small>Join <%= time_ago_in_words(user.created_at) %> ago  </small>
                    </div>
            </div>
          </div>
        </div>
    <% end %>
</div>

<div class="flickr_pagination mt-4 mb-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sing up for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"> <%= @user.username %>'s Profile </h1>
<%= gravatar_for @user, size:200%>

<h1 class="text-center mt-4"> <%= @user.username %>'s Articles </h1>

<div class="text-center mt-4">
    <% if logged_in? && current_user == @user %>
      <%= link_to "Edit your profile", edit_user_path(@user), class:"btn btn-outline-success" %>
    <% end %>
</div>

<div class="flickr_pagination mt-4">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles/article' %>

<div class="flickr_pagination mt-4 mb-4">
  <%= will_paginate @articles, :container => false %>
</div>